name: 'dual_nback'
version: 0.0.1
description: >
  An absolute bare-bones web app.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.9.1'
dependencies:
  browser: any
  uix:
    git: git://github.com/localvoid/uix.git
